config/routes.rb
Rails.application.routes.draw do
  root 'schools#index'

  resources :employees
  resources :positions
  resources :assignments
  resources :students
  resources :schools
  resources :degrees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/degree.rb
class Degree < ApplicationRecord
  validates :name, :school_id, presence: true
  has_many :students
  belongs_to :school
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :set_degree, only: %i[ show edit update destroy ]

  # GET /degrees or /degrees.json
  def index
    @degrees = Degree.all
  end

  # GET /degrees/1 or /degrees/1.json
  def show
  end

  # GET /degrees/new
  def new
    @degree = Degree.new
  end

  # GET /degrees/1/edit
  def edit
  end

  # POST /degrees or /degrees.json
  def create
    @degree = Degree.new(degree_params)

    respond_to do |format|
      if @degree.save
        format.html { redirect_to degree_url(@degree), notice: "Degree was successfully created." }
        format.json { render :show, status: :created, location: @degree }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degrees/1 or /degrees/1.json
  def update
    respond_to do |format|
      if @degree.update(degree_params)
        format.html { redirect_to degree_url(@degree), notice: "Degree was successfully updated." }
        format.json { render :show, status: :ok, location: @degree }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degrees/1 or /degrees/1.json
  def destroy
    @degree.destroy

    respond_to do |format|
      format.html { redirect_to degrees_url, notice: "Degree was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree
      @degree = Degree.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def degree_params
      params.require(:degree).permit(:name, :school_id)
    end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/views/degrees/_form.html.erb
<%= form_with(model: degree) do |form| %>
  <% if degree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(degree.errors.count, "error") %> prohibited this degree from being saved:</h2>

      <ul>
        <% degree.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :school_id %>
    <%= form.number_field :school_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/degrees/edit.html.erb
<h1>Editing Degree</h1>

<%= render 'form', degree: @degree %>

<%= link_to 'Show', @degree %> |
<%= link_to 'Back', degrees_path %>

app/views/degrees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Degrees</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>school_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @degrees.each do |degree| %>
      <tr>
        <td><%= degree.name %></td>
        <td><%= degree.school_id %></td>
        <td><%= link_to 'Show', degree %></td>
        <td><%= link_to 'Edit', edit_degree_path(degree) %></td>
        <td><%= link_to 'Destroy', degree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degree', new_degree_path %>

app/views/degrees/new.html.erb
<h1>New Degree</h1>

<%= render 'form', degree: @degree %>

<%= link_to 'Back', degrees_path %>

app/views/degrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @degree.name %>
</p>

<p>
  <strong>School_id</strong>
  <%= @degree.school_id %>
</p>

<%= link_to 'Edit', edit_degree_path(@degree) %> |
<%= link_to 'Back', degrees_path %>

<h3>Degree students</h3>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Birth date</th>
      <th>Address</th>
      <th>Degree_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students = @degree.students %>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
        <td><%= student.phone_number %></td>
        <td><%= student.birth_date %></td>
        <td><%= student.address %></td>
        <td><%= student.degree_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>